//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ЖКХ
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contract
    {
        public int ContractID { get; set; }
        public int ResidentID { get; set; }
        public int ManagementCompanyID { get; set; }
        public System.DateTime ContractDate { get; set; }
    
        public virtual ManagementCompany ManagementCompany { get; set; }
        public virtual Resident Resident { get; set; }
    }
}
