//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ЖКХ
{
    using System;
    using System.Collections.Generic;
    
    public partial class MeterReading
    {
        public int ReadingID { get; set; }
        public int MeterID { get; set; }
        public decimal ReadingValue { get; set; }
        public System.DateTime ReadingDate { get; set; }
    
        public virtual Meter Meter { get; set; }
    }
}
