//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ЖКХ
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities1 : DbContext
    {
        public Entities1()
            : base("name=Entities1")
        {
        }
        private static Entities1 _context;
        public static Entities1 Getcontext()
        {
            if (_context == null) _context = new Entities1();
            return _context;
        }


        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Apartment> Apartments { get; set; }
        public virtual DbSet<Building> Buildings { get; set; }
        public virtual DbSet<Contract> Contracts { get; set; }
        public virtual DbSet<ManagementCompany> ManagementCompanies { get; set; }
        public virtual DbSet<MeterReading> MeterReadings { get; set; }
        public virtual DbSet<Meter> Meters { get; set; }
        public virtual DbSet<Payment> Payments { get; set; }
        public virtual DbSet<Request> Requests { get; set; }
        public virtual DbSet<Resident> Residents { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<Service> Services { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Вызовы> Вызовы { get; set; }
        public virtual DbSet<Жалобы> Жалобы { get; set; }
        public virtual DbSet<Жильцы> Жильцы { get; set; }
        public virtual DbSet<Заявки> Заявки { get; set; }
        public virtual DbSet<Квартиры> Квартиры { get; set; }
        public virtual DbSet<Платежи> Платежи { get; set; }
        public virtual DbSet<Работники> Работники { get; set; }
        public virtual DbSet<Расходы> Расходы { get; set; }
        public virtual DbSet<Счета> Счета { get; set; }
        public virtual DbSet<Услуги> Услуги { get; set; }
    }
}
