//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ЖКХ
{
    using System;
    using System.Collections.Generic;
    
    public partial class Request
    {
        public int RequestID { get; set; }
        public int ResidentID { get; set; }
        public int ServiceID { get; set; }
        public System.DateTime RequestDate { get; set; }
        public string Description { get; set; }
        public string Status { get; set; }
    
        public virtual Resident Resident { get; set; }
        public virtual Service Service { get; set; }
    }
}
