//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ЖКХ
{
    using System;
    using System.Collections.Generic;
    
    public partial class Жильцы
    {
        public int id { get; set; }
        public string ФИО { get; set; }
        public Nullable<System.DateTime> дата_рождения { get; set; }
        public string паспортные_данные { get; set; }
        public Nullable<int> номер_квартиры { get; set; }
    
        public virtual Квартиры Квартиры { get; set; }
    }
}
